### ISSUE TITLE
error while opening app

### ISSUE THREAD

**Issue by akvareli2** [nightscout/nightscout.github.io#162]
Errors occurred during startup:

Unable to setup authorization
{"stack":"MongoError: user is not allowed to do action [find] on [test.auth_roles]
at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:266:20)
at MessageStream.emit (node:events:513:28)
at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
at writeOrBuffer (node:internal/streams/writable:391:12)
at _write (node:internal/streams/writable:332:10)
at MessageStream.Writable.write (node:internal/streams/writable:336:10)
at TLSSocket.ondata (node:internal/streams/readable:754:22)
at TLSSocket.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:315:12)","message":"user is not allowed to do action [find] on [test.auth_roles]","ok":0,"code":8000,"codeName":"AtlasError","name":"MongoError"}
![tempImageeIdtq0](https://user-images.githubusercontent.com/116201462/196901870-91be7537-0049-4656-af5b-cb3c78e17024.gif)
<img width="1093" alt="Знімок екрана 2022-10-20 о 11 45 01" src="https://user-images.githubusercontent.com/116201462/196903175-279a724f-4c1f-4983-8db7-ecc230425527.png">

**Comment by psonnera** [comment]
Which database are you using?

**Comment by akvareli2** [comment]
Mongo DB

**Comment by psonnera** [comment]
You mean Atlas?

**Comment by akvareli2** [comment]
this 
<img width="1330" alt="Знімок екрана 2022-10-20 о 13 12 14" src="https://user-images.githubusercontent.com/116201462/196921893-c4536e2d-fe22-495c-add5-83d2abc94f37.png">

**Comment by psonnera** [comment]
Perfect, can you check your database user has all rights? https://nightscout.github.io/troubleshoot/atlas/#mongodb-in-read-only-mode

**Comment by akvareli2** [comment]
I added admin rights. Now everything is fine. Thanks a lot!

**Comment by psonnera** [comment]
Great!
