### ISSUE TITLE
Nightscout Boot Error

### ISSUE THREAD

**Issue by JimZam** [nightscout/nightscout.github.io#64]
Good morning. My Nightscout herokuapp.com has been working since I created it ten days ago. Now it shows an error message. Could you please help me to solve it?
Thank you in advance
Regards

Edit: it seems to be related to AUTH_DEFAULT_ROLES denied. If I delete this variable and enable it again it works, don't know for how long...

Nightscout - Boot Error

Unable to setup authorization
    {"name":"MongoNetworkError","message":"connection 0 to ds157956.mlab.com:57956 timed out","stack":"MongoNetworkError: connection 0 to ds157956.mlab.com:57956 timed out
    at Socket. (/app/node_modules/mongodb-core/lib/connection/connection.js:258:7)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:410:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)"}

**Comment by psonnera** [comment]
@JimZam please confirm it could have been fixed using https://nightscout.github.io/troubleshoot/troublehoot/ (that was not available at that time) or let me know what the solution/issue was.
